# Generated by Django 4.1.5 on 2023-01-26 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
